### ISSUE TITLE
this library breaks the sage 9 sage cli / post install process

### ISSUE THREAD

**Issue by jmp909** [Log1x/sage-directives#4]
on windows we need to run the sage post install process manually

ie `vendor\bin\sage.bat preset` etc

however this throws the following error

```php
PHP Fatal error:  Uncaught Error: Call to undefined function App\Directives\add_action() in D:\dev\test\roots\bedrock\web\app\themes\sage\vendor\log1x\sage-directives\src\Directives.php:48
Stack trace:
#0 D:\dev\test\roots\bedrock\web\app\themes\sage\vendor\log1x\sage-directives\src\Directives.php(73): App\Directives\Directives->__construct()
#1 D:\dev\test\roots\bedrock\web\app\themes\sage\vendor\composer\autoload_real.php(66): require('D:\\dev\\test\\roo...')
#2 D:\dev\test\roots\bedrock\web\app\themes\sage\vendor\composer\autoload_real.php(56): composerRequire252af4a6338f1ee1f66c597f9df2708d('306c972fefb7062...', 'D:\\dev\\test\\roo...')
#3 D:\dev\test\roots\bedrock\web\app\themes\sage\vendor\autoload.php(7): ComposerAutoloaderInit252af4a6338f1ee1f66c597f9df2708d::getLoader()
#4 D:\dev\test\roots\bedrock\web\app\themes\sage\vendor\roots\sage-installer\bin\sage(5): include_once('D:\\dev\\test\\roo...')
#5 {main}  thrown in D:\dev\test\roots\bedrock\web\app\themes\sage\vendor\log1x\sage-directives\src\Directives.php on line 48
```

please advise,
thanks
J

**Comment by Log1x** [comment]
Weird. I'll push an update shortly to check for `function_exists()` on `add_action()` to prevent unexpected behavior when it is not able to load WordPress' core.

**Edit:** Try out [v1.0.3](https://github.com/Log1x/sage-directives/releases/tag/v1.0.3) and let me know if that fixes the issue. Thanks!
